minimumReleaseAgeExclude:
  - '@oxc-project/types@0.133.0'
  - '@rolldown/binding-android-arm64@1.0.3'
  - '@rolldown/binding-darwin-arm64@1.0.3'
  - '@rolldown/binding-darwin-x64@1.0.3'
  - '@rolldown/binding-freebsd-x64@1.0.3'
  - '@rolldown/binding-linux-arm-gnueabihf@1.0.3'
  - '@rolldown/binding-linux-arm64-gnu@1.0.3'
  - '@rolldown/binding-linux-arm64-musl@1.0.3'
  - '@rolldown/binding-linux-ppc64-gnu@1.0.3'
  - '@rolldown/binding-linux-s390x-gnu@1.0.3'
  - '@rolldown/binding-linux-x64-gnu@1.0.3'
  - '@rolldown/binding-linux-x64-musl@1.0.3'
  - '@rolldown/binding-openharmony-arm64@1.0.3'
  - '@rolldown/binding-wasm32-wasi@1.0.3'
  - '@rolldown/binding-win32-arm64-msvc@1.0.3'
  - '@rolldown/binding-win32-x64-msvc@1.0.3'
  - rolldown@1.0.3
  - tinyglobby@0.2.17
  - vite@8.0.16
